"--------------
" Neovim Compatibility
"--------------
" Detect if running in Neovim
let g:is_nvim = has('nvim')

" Neovim-specific optimizations
if g:is_nvim
  " Use true colors in neovim (better color support)
  set termguicolors

  " Better cursor shape in different modes
  set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50

  " Enable more powerful completion
  set completeopt=menu,menuone,noselect
endif

"--------------
" Plugins
"--------------
call plug#begin('~/.config/nvim/plugged')
  " for general purpose development
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'scrooloose/nerdtree'
  Plug 'ctrlpvim/ctrlp.vim'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-repeat'
  Plug 'terryma/vim-multiple-cursors'
  Plug 'tomtom/tcomment_vim'
  Plug 'majutsushi/tagbar'
  Plug 'mileszs/ack.vim'
  Plug 'airblade/vim-gitgutter'
  " for general purpose, snipmate, snippets
  Plug 'MarcWeber/vim-addon-mw-utils'
  Plug 'tomtom/tlib_vim'
  Plug 'garbas/vim-snipmate'
  Plug 'honza/vim-snippets'
  " for language server protocol
  Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': 'bash install.sh' }

  " for markdown
  Plug 'godlygeek/tabular'
  Plug 'plasticboy/vim-markdown'

  " for python
  Plug 'davidhalter/jedi-vim'

  " for C#
  Plug 'OmniSharp/omnisharp-vim'

  " for AI assistance
  Plug 'github/copilot.vim'

  " for EditorConfig support
  Plug 'editorconfig/editorconfig-vim'

call plug#end()

"--------------
" Settings
"--------------
set nocompatible
set clipboard=unnamedplus  " Use system clipboard (+ register)
set noswapfile
set hidden
set nobomb            " no BOM(Byte Order Mark)
set mouse=a

"--------------
" Filetype and Encoding
"--------------
filetype on
filetype indent on
filetype plugin on

" file encoding
set encoding=utf-8
scriptencoding utf-8

"--------------
" key mapping
"--------------
let mapleader = ","

